openapi: 3.1.1
info:
  title: Testing API
  version: '1.0.0'
paths:
  /users:
    post:
      summary: creates user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  description: name of the user
                  type: string
                email:
                  description: email of the user
                  type: string
                password:
                  description: password of the user
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: user created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    description: id of the created user
                    type: string
                  username:
                    description: name of the user
                    type: string
                  email:
                    description: email of the user
                    type: string
                required:
                  - id
                  - username
                  - email