name: Run Tests for testing-example

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24.8.0'
          cache: 'npm'
          cache-dependency-path: './testing-example/package-lock.json'

      - name: Install Dependencies
        working-directory: ./testing-example
        run: npm ci

      - name: Run Tests
        working-directory: ./testing-example
        run: npm test      

